### PR TITLE
tt: Add Options Class, used for parsing commandline options

### PR DESCRIPTION
**Pull request by Cogitri**
Not sure if this is quite what we want for the CLI but I figured this is a good start :)

### CODE REVIEW

**Comment by Cogitri** [comment]
Seems like CodeCov doesn't work for PRs

**Comment by Cogitri** [comment]
I guess you'll have to enable the codecov token for PRs too so we can see a Codecov report for PRs.

**Comment by DanySpin97** [comment]
> Not sure if this is quite what we want for the CLI but I figured this is a good start :)

Indeed it is :)

> I guess you'll have to enable the codecov token for PRs too so we can see a Codecov report for PRs.

I can't find where it should be added. Maybe a `.codecov.yaml` file is missing with the config for the PR.

**Comment by Cogitri** [comment]
Ah no, you'd have to enable that in GitHub settings so that the codecov token is enable for LRs too

**Comment by Cogitri** [comment]
I added it like this:

Screenshot from 2020-01-21 09-58-59

**Pull request merged**
