### PR TITLE
 tree-wide: use const, @safe and nothrow where possible.

### PR DESCRIPTION
**Pull request by Cogitri**
Also run dfmt over the source. It'd be good if this is always done (and maybe a CI job would make sense)

### CODE REVIEW

**Comment by Cogitri** [comment]
CI passes now, just codecov failing once again.

**Comment by DanySpin97** [comment]
> It'd be good if this is always done

We could also use git hooks.

> CI passes now, just codecov failing once again.

I guess it cannot find the token because it is run from your repository (where no token was set).

**Comment by Cogitri** [comment]
> I guess it cannot find the token because it is run from your repository (where no token was set).

Yup, it's kind of unfortunate that Github Secrets don't support sharing secret. I could make a branch on this repo and file a PR from that for it to work, I suppose.

**Comment by Cogitri** [comment]
> We could also use git hooks.

Yes, that'd work

**Pull request merged**
